# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-02 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingIcetray',
            fields=[
                ('db_key', models.AutoField(primary_key=True, serialize=False)),
                ('db_owner', models.CharField(db_index=True, max_length=80)),
                ('db_currency', models.CharField(max_length=80)),
                ('db_value', models.DecimalField(default=0)),
                ('db_reason', models.TextField(blank=True)),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=b'date created')),
            ],
            options={
                'ordering': 'db_date_created',
            },
        ),
        migrations.CreateModel(
            name='AccountingJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_owner', models.CharField(db_index=True, max_length=80)),
                ('db_currency', models.CharField(max_length=80)),
                ('db_initial', models.DecimalField(default=0)),
                ('db_value', models.DecimalField(default=0)),
                ('db_accrued', models.DecimalField(default=0)),
                ('db_date_created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountingLog',
            fields=[
                ('db_key', models.AutoField(primary_key=True, serialize=False)),
                ('db_owner', models.CharField(db_index=True, max_length=80)),
                ('db_currency', models.CharField(max_length=80)),
                ('db_value', models.DecimalField(default=0)),
                ('db_reason', models.TextField(blank=True)),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=b'date created')),
            ],
            options={
                'ordering': 'db_date_created',
            },
        ),
    ]
