# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-04 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sr5', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('AccountingJournal', 'Ledger')
    ]
