# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-05 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sr5', '0002_auto_20170804_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingicetray',
            options={'ordering': ('db_date_created',)},
        ),
        migrations.AlterModelOptions(
            name='accountinglog',
            options={'ordering': ('db_date_created',)},
        ),
        migrations.AddField(
            model_name='accountingicetray',
            name='db_origin',
            field=models.CharField(default='#1', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountinglog',
            name='db_origin',
            field=models.CharField(default='#1', max_length=80),
            preserve_default=False,
        ),
    ]
